//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSinhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class diemdanh
    {
        public int madiemdanh { get; set; }
        public int mahocsinh_hoatdong { get; set; }
        public System.DateTime ngaydiemdanh { get; set; }
        public bool comat { get; set; }
        public bool denmuon { get; set; }
    
        public virtual hocsinh_hoatdong hocsinh_hoatdong { get; set; }
    }
}
