//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSinhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoatdong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoatdong()
        {
            this.hocsinh_hoatdong = new HashSet<hocsinh_hoatdong>();
        }
    
        public int mahoatdong { get; set; }
        public string ten { get; set; }
        public System.DateTime ngaybatdau { get; set; }
        public System.DateTime ngayketthuc { get; set; }
        public Nullable<int> soluongtoida { get; set; }
        public string mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hocsinh_hoatdong> hocsinh_hoatdong { get; set; }
    }
}
