//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSinhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoidung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nguoidung()
        {
            this.hocsinh_hoatdong = new HashSet<hocsinh_hoatdong>();
        }
    
        public int manguoidung { get; set; }
        public string hoten { get; set; }
        public string tendangnhap { get; set; }
        public string email { get; set; }
        public string matkhau { get; set; }
        public bool lahocsinh { get; set; }
        public bool bikhoa { get; set; }
        public string tenlop { get; set; }
        public string cccd { get; set; }
        public bool gioitinh { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public string quocgia { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
        public string quoctich { get; set; }
        public string chuyennganh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hocsinh_hoatdong> hocsinh_hoatdong { get; set; }
    }
}
